In [61]:
import pandas as pd
import numpy as np
import pickle

In [44]:
dataset = pd.read_csv("out.csv")

In [45]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0             1            0         0       1             1             0   
1             1            1         0       1             0             0   
2             1            1         0       0             0             1   
3             1            0         1       0             1             0   
4             1            1         1       0             0             0   
...         ...          ...       ...     ...           ...           ...   
1015          0            1         1       1             0             0   
1016          0            1         1       1             0             0   
1017          1            0         1       1             0             0   
1018          1            1         0       0             1             0   
1019          1            0         1       0             0             1   

      Naturalist  Spatial  Linguistic  Intrapersonal  Bodily-Kinesthetic  \
0              0        1           1              1                   0   
1              1        0           0              1                   1   
2              1        1           0              0                   0   
3              0        0           1              1                   0   
4              1        1           1              0                   0   
...          ...      ...         ...            ...                 ...   
1015           0        0           0              1                   1   
1016           0        1           0              0                   1   
1017           1        0           0              1                   0   
1018           0        1           1              0                   0   
1019           0        0           1              1                   0   

      Musical  Logical-mathematical  Interpersonal  Math  English  Science  \
0           0                     0              0    94       86      100   
1           0                     0              0    81       98       90   
2           1                     0              0    83       90       80   
3           0                     0              1   100       96       84   
4           0                     0              0    85       93       97   
...       ...                   ...            ...   ...      ...      ...   
1015        1                     0              0    97       94      100   
1016        1                     0              0    84       85       85   
1017        0                     0              1    86       95       92   
1018        0                     1              0    98       97       84   
1019        1                     0              0    95       83       92   

      Social Science  Class  
0                100      1  
1                 93      2  
2                 97      0  
3                 85      1  
4                 95      2  
...              ...    ...  
1015              93      2  
1016              84      1  
1017              96      2  
1018              91      0  
1019              91      2  

[1020 rows x 19 columns]

In [46]:
X = dataset.iloc[:, 0:18].values
y = dataset.iloc[:, 18].values

In [47]:
X.shape

(1020, 18)

In [66]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [75]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

X_train





In [76]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [77]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[32 20 10]
 [29 25 20]
 [32 22 14]]
              precision    recall  f1-score   support

           0       0.34      0.52      0.41        62
           1       0.37      0.34      0.35        74
           2       0.32      0.21      0.25        68

    accuracy                           0.35       204
   macro avg       0.35      0.35      0.34       204
weighted avg       0.35      0.35      0.34       204

0.3480392156862745


In [78]:
filename = 'random_forest_model.sav'
pickle.dump(regressor, open(filename, 'wb'))


In [79]:
pickle.dump(sc, open('scaler.pkl','wb'))